### ISSUE TITLE
This app is not working for me

### ISSUE THREAD

**Issue by garek007** [zoom/webhook-sample-node.js#1]
I've tried the deploy button. That seemed easy, but it won't validate in my zoom dev panel. So I tried to clone the app, but I'm getting an error "Repository not found" even though I copied it straight from the page. 

```
remote: Repository not found.
fatal: repository 'https://github.com/zoom/webhook-sample.node.js.git/' not found
salachniewicz@salachn-ltm8brj heroku % 
```

**Comment by tommygaessler** [comment]
Hey @garek007 , strange, can you please try again? I just tried and it worked.

**Comment by garek007** [comment]
Well I was able to do it the manual way, by downloading the zip and then copy/pasting. I can still try if you'd like me to do so, in order to test.

**Comment by tommygaessler** [comment]
Hey @garek007 , that would be great so we can verify that it is functioning properly.

**Comment by garek007** [comment]
Ok well now it works... odd. But I am running into another issue. I still can't get it to validate my webhook app URL and I've been debugging and it seems that my signature and header do not match, so maybe the hash is wrong? I created a new issue on the forum here if you want the details https://devforum.zoom.us/t/event-notification-endpoint-url-url-validation-failed-try-again-later-webhook-only-app/74014/2

**Comment by tommygaessler** [comment]
Thanks @garek007, glad to hear the deploy flow is working. I will support you over on the forum about the validation piece.
